$targets = @(
  'FE_KNGS/web-reactjs/src/api/axiosClient.js',
  'FE_KNGS/web-reactjs/src/components/Header/HeaderAdmin/index.jsx',
  'FE_KNGS/web-reactjs/src/components/MenuHeader.jsx',
  'FE_KNGS/web-reactjs/src/components/Login.jsx',
  'FE_KNGS/web-reactjs/src/pages/tutor/ManageBookings/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/home/ListTutorPage/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/tutor/ConnectedClasses/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/student/Profile/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/student/ManagePosts/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/student/ManageBookings/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/admin/StudentManagement/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/student/ConnectedClasses/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/admin/PostManagement/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/admin/ClassManagement/index.jsx',
  'FE_KNGS/web-reactjs/src/pages/admin/BookingManagement/index.jsx'
)

$replacements = @(
  @('Lá»—i', 'Lỗi'),
  @('lá»—i', 'lỗi'),
  @('ÄÃ£', 'Đã'),
  @('ÄÃƒ', 'ĐÃ'),
  @('Äóng', 'Đóng'),
  @('ÄÃ³ng', 'Đóng'),
  @('Äang', 'Đang'),
  @('ÄANG', 'ĐANG'),
  @('Báº¡n', 'Bạn'),
  @('báº¡n', 'bạn'),
  @('cháº¯c cháº¯n', 'chắc chắn'),
  @('muá»‘n', 'muốn'),
  @('xÃ³a', 'xóa'),
  @('XÃ³a', 'Xóa'),
  @('há»§y', 'hủy'),
  @('Há»§y', 'Hủy'),
  @('khÃ´ng', 'không'),
  @('KhÃ´ng', 'Không'),
  @('vui lÃ²ng', 'vui lòng'),
  @('Vui lÃ²ng', 'Vui lòng'),
  @('nháº­p', 'nhập'),
  @('Nháº­p', 'Nhập'),
  @('yÃªu cáº§u', 'yêu cầu'),
  @('YÃªu cáº§u', 'Yêu cầu'),
  @('pháº£n há»“i', 'phản hồi'),
  @('Pháº£n há»“i', 'Phản hồi'),
  @('thÃ nh cÃ´ng', 'thành công'),
  @('ThÃ nh cÃ´ng', 'Thành công'),
  @('THÃ€NH CÃ”NG', 'THÀNH CÔNG'),
  @('tháº¥t báº¡i', 'thất bại'),
  @('Tháº¥t báº¡i', 'Thất bại'),
  @('hä»c', 'học'),
  @('há»c', 'học'),
  @('Há»c', 'Học'),
  @('viÃªn', 'viên'),
  @('ViÃªn', 'Viên'),
  @('Há»c viÃªn', 'Học viên'),
  @('hä»c viÃªn', 'học viên'),
  @('GiÃ¡o viÃªn', 'Giáo viên'),
  @('giÃ¡o viÃªn', 'giáo viên'),
  @('Sinh viÃªn', 'Sinh viên'),
  @('sinh viÃªn', 'sinh viên'),
  @('Gia sÆ°', 'Gia sư'),
  @('gia sÆ°', 'gia sư'),
  @('Äá»“ng Ã½', 'Đồng ý'),
  @('Ä‘á»“ng Ã½', 'đồng ý'),
  @('Tá»« chá»‘i', 'Từ chối'),
  @('Tá»ª CHá»I', 'TỪ CHỐI'),
  @('tráº¡ng thÃ¡i', 'trạng thái'),
  @('Tráº¡ng thÃ¡i', 'Trạng thái'),
  @('kết ná»‘i', 'kết nối'),
  @('káº¿t ná»‘i', 'kết nối'),
  @('Káº¿t ná»‘i', 'Kết nối'),
  @('Káº¾T Ná»I', 'KẾT NỐI'),
  @('hoÃ n thÃ nh', 'hoàn thành'),
  @('HoÃ n thÃ nh', 'Hoàn thành'),
  @('HOÃ€N THÃ€NH', 'HOÀN THÀNH'),
  @('hoÃ n tiá»n', 'hoàn tiền'),
  @('HoÃ n tiá»n', 'Hoàn tiền'),
  @('HOÃ€N TIá»€N', 'HOÀN TIỀN'),
  @('thanh toÃ¡n', 'thanh toán'),
  @('Thanh toÃ¡n', 'Thanh toán'),
  @('THANH TOÃN', 'THANH TOÁN'),
  @('cá»•ng', 'cổng'),
  @('Cá»•ng', 'Cổng'),
  @('há»‡ thá»‘ng', 'hệ thống'),
  @('Há»‡ thá»‘ng', 'Hệ thống'),
  @('quáº£n lÃ½', 'quản lý'),
  @('Quáº£n lÃ½', 'Quản lý'),
  @('danh sÃ¡ch', 'danh sách'),
  @('Danh sÃ¡ch', 'Danh sách'),
  @('bÃ i Ä‘Äƒng', 'bài đăng'),
  @('BÃ i Ä‘Äƒng', 'Bài đăng'),
  @('chi tiáº¿t', 'chi tiết'),
  @('Chi tiáº¿t', 'Chi tiết'),
  @('Ä‘á»‹a chá»‰', 'địa chỉ'),
  @('Äá»‹a chá»‰', 'Địa chỉ'),
  @('mÃ´n há»c', 'môn học'),
  @('MÃ´n há»c', 'Môn học'),
  @('trÃ¬nh Ä‘á»™', 'trình độ'),
  @('TrÃ¬nh Ä‘á»™', 'Trình độ'),
  @('giá»›i tÃ­nh', 'giới tính'),
  @('Giá»›i tÃ­nh', 'Giới tính'),
  @('giá»', 'giờ'),
  @('Giá»', 'Giờ'),
  @('buá»•i', 'buổi'),
  @('Buá»•i', 'Buổi'),
  @('tuáº§n', 'tuần'),
  @('ngÃ y', 'ngày'),
  @('NgÃ y', 'Ngày'),
  @('thá»i lÆ°á»£ng', 'thời lượng'),
  @('Thá»i lÆ°á»£ng', 'Thời lượng'),
  @('sá»‘', 'số'),
  @('Sá»‘', 'Số'),
  @('liÃªn há»‡', 'liên hệ'),
  @('LiÃªn há»‡', 'Liên hệ'),
  @('giá»›i thiá»‡u', 'giới thiệu'),
  @('Giá»›i thiá»‡u', 'Giới thiệu'),
  @('ghi chÃº', 'ghi chú'),
  @('Ghi chÃº', 'Ghi chú'),
  @('Ä‘iá»‡n thoáº¡i', 'điện thoại'),
  @('Äiá»‡n thoáº¡i', 'Điện thoại'),
  @('Ä‘iá»ƒm uy tÃ­n', 'điểm uy tín'),
  @('Äiá»ƒm uy tÃ­n', 'Điểm uy tín'),
  @('há»“ sÆ¡', 'hồ sơ'),
  @('Há»“ sÆ¡', 'Hồ sơ'),
  @('Ä‘iá»ƒm', 'điểm'),
  @('Äiá»ƒm', 'Điểm'),
  @('Ä‘Æ°á»£c', 'được'),
  @('ÄÆ°á»£c', 'Được'),
  @('sáº½', 'sẽ'),
  @('cáº§n', 'cần'),
  @('Cáº§n', 'Cần'),
  @('Ã¡p dá»¥ng', 'áp dụng'),
  @('Ãp dá»¥ng', 'Áp dụng'),
  @('má»Ÿ', 'mở'),
  @('Má»Ÿ', 'Mở'),
  @('khÃ³a', 'khóa'),
  @('KhÃ³a', 'Khóa'),
  @('mÃ£ giao dá»‹ch', 'mã giao dịch'),
  @('MÃ£ GD', 'Mã GD'),
  @('mÃ£ QR', 'mã QR'),
  @('ngÃ¢n hÃ ng', 'ngân hàng'),
  @('tÃ i khoáº£n', 'tài khoản'),
  @('Há»— trá»£', 'Hỗ trợ'),
  @('há»— trá»£', 'hỗ trợ'),
  @('Nháº­n', 'Nhận'),
  @('nháº­n', 'nhận'),
  @('LÃ½ do', 'Lý do'),
  @('lÃ½ do', 'lý do'),
  @('CHÆ¯A', 'CHƯA'),
  @('ÄANG', 'ĐANG'),
  @('ÄÃƒ HOÃ€N Táº¤T PHÃ', 'ĐÃ HOÀN TẤT PHÍ'),
  @('ÄANG CHá»œ', 'ĐANG CHỜ'),
  @('CHá»œ', 'CHỜ'),
  @('ÄÃƒ Há»¦Y', 'ĐÃ HỦY'),
  @('Bá»Š Tá»ª CHá»I', 'BỊ TỪ CHỐI'),
  @('ÄANG Káº¾T Ná»I', 'ĐANG KẾT NỐI'),
  @('Má»šI Táº O', 'MỚI TẠO'),
  @('CHá»œ GIA SÆ¯', 'CHỜ GIA SƯ'),
  @('CHá»œ GIA SÆ¯ TRáº¢ Lá»œI', 'CHỜ GIA SƯ TRẢ LỜI'),
  @('Táº¡i nhÃ ', 'Tại nhà'),
  @('Trá»±c tuyáº¿n', 'Trực tuyến'),
  @('kÃ­ch hoáº¡t', 'kích hoạt'),
  @('KÃ­ch hoáº¡t', 'Kích hoạt'),
  @('cáº£nh cÃ¡o', 'cảnh cáo'),
  @('Cáº£nh cÃ¡o', 'Cảnh cáo'),
  @('KhÃ´ng cÃ³', 'Không có'),
  @('ChÆ°a', 'Chưa'),
  @('chÆ°a', 'chưa'),
  @('lÆ°u', 'lưu'),
  @('LÆ°u', 'Lưu'),
  @('thay Ä‘á»•i', 'thay đổi'),
  @('Thay Ä‘á»•i', 'Thay đổi'),
  @('Ä‘Ã¡nh giÃ¡', 'đánh giá'),
  @('ÄÃ¡nh giÃ¡', 'Đánh giá'),
  @('viáº¿t Ä‘Ã¡nh giÃ¡', 'viết đánh giá'),
  @('Sá»­a Ä‘Ã¡nh giÃ¡', 'Sửa đánh giá'),
  @('Xá»­ lÃ½', 'Xử lý'),
  @('xá»­ lÃ½', 'xử lý'),
  @('Ä‘Æ¡n tiá»n', 'đơn tiền'),
  @('Ä‘iá»u kiá»‡n', 'điều kiện'),
  @('vÃ­ dá»¥', 'ví dụ'),
  @('VÃ­ dá»¥', 'Ví dụ')
)

foreach ($target in $targets) {
  $path = Join-Path $PWD $target
  if (-not (Test-Path $path)) { continue }
  $content = Get-Content -Raw -Path $path
  foreach ($replacement in $replacements) {
    $content = $content.Replace($replacement[0], $replacement[1])
  }
  Set-Content -Path $path -Value $content -Encoding utf8
}
